### ISSUE TITLE
init w_add_out_dim and w_add_in_dim as zeros will prevent the opponent from performing gradient updates.

### ISSUE THREAD

**Issue by TtuHamg** [JJuOn/LFS-GAN#2]
hi, i notice that the w_add_out_dim and w_add_in_dim are Initialized as zeros. However, due to w_add_out_dim @ w_add_in_dim  in your code, does this result in the gradient itself being zero, since calculating the gradient requires the parameters of the other party? Hope to receive your reply, thank you.
![image](https://github.com/JJuOn/LFS-GAN/assets/95615492/50a3df69-937a-400e-9740-d0f54206b619)
![image](https://github.com/JJuOn/LFS-GAN/assets/95615492/03ba5226-2845-43b6-8719-bfe99d00d94a)

**Comment by JJuOn** [comment]
Hi, sorry for the late response.
As you pointed out, I made some mistakes in preparing the public code.
You can replace `zeros` with  `randn * eps`.

Moreover, I found that there are mistakes in the uploaded checkpoints.
I will re-upload soon.

**Comment by TtuHamg** [comment]
Okay, thank you for your reply. I have another small question I'd like to ask you. When using the LoRa method to decompose the modulation matrix W, the initialization method for the two low-rank matrices appears to be the same, which seems to result in identical parameter values for each row of each low-rank matrix. Do you think this kind of initialization might pose a problem?
Here is my visualization for another model that used your method. I print the first row of lora rank of W and the rank is 2.
<img width="563" alt="a699cdce4fcd8b61e3acd97a79bc6db" src="https://github.com/JJuOn/LFS-GAN/assets/95615492/f3fa4451-4c73-41bc-a89d-8e03a11e72db">

**Comment by JJuOn** [comment]
As you mentioned, the initialization of LoRA and the addition parameters in our LeFT (referred to as "add") are similar.

We set $\Gamma$ and $B$ (reconstructed from LeFT's decomposed parameters) to be close to 1 and 0, respectively, in the early training iterations.
We adopted this strategy to produce results similar to those of the pre-trained network.
Otherwise, in a few-shot setting, the training becomes highly unstable.

Therefore, this kind of initialization is effective.
I recommend referring to another repository ([AdAM](https://github.com/yunqing-me/AdAM)).
